version: '3.9'

services:
  webform:
    build: .
    command: sh -c "sleep 10s ; python3 ./app.py"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=webform
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'webform'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./webform.sql:/docker-entrypoint-initdb.d/webform.sql
    ports:
      - '3307:3306'  # Map MySQL service to a different local port (3307) to avoid conflicts

